services:
  web:
    tty: true
    image: oven/bun:latest
    container_name: electeer-web
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    working_dir: /app/packages/web
    command: bun run dev
    restart: unless-stopped
